### ISSUE TITLE
Long text overflows the container

### ISSUE THREAD

**Issue by gnarf** [jquery/blog.jquery.com-theme#3]
Captured from http://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/ on my nexus 5

![screenshot_2014-07-03-11-38-34](https://cloud.githubusercontent.com/assets/549355/3472419/8a4ef550-02cb-11e4-89b1-8fddf539aa34.png)

Pretty sure we fixed this problem in the main wp-content theme already

**Comment by Krinkle** [comment]
Works for me now. I'm guessing one of the commits syncing with jquery-wp-content fixed this.

<img width="250" alt="Screenshot" src="https://github.com/jquery/blog.jquery.com-theme/assets/156867/9f33a4db-fd92-46f3-ab16-c3bb464b89fe">

For the long-term, I've proposed un-forking this theme with jquery-wp-content, tracked at https://github.com/jquery/infrastructure/issues/541 (private).
